[[pages]]
path = "main.py"
name = "Login"
icon = ":books:"

[[pages]]
path = "app/interfaces/ui/pages/Criar_usuário.py"
name = "Criar usuário"
icon = ":books:"

[[pages]]
path = "app/interfaces/ui/pages/Lancamentos.py"
name = "Lancamentos"
icon = ":books:"

[[pages]]
path = "app/interfaces/ui/pages/Criar_categoria.py"
name = "Categoria"
icon = ":books:"
